[
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": 75,
      "Fornecedor": "null",
      "EmbalagemReferencia": "kg",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 5,
      "Comprador": "Antonio Vanderlei S Silveira",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Feijão Preto Caldo Nobre Tipo 1 1kg",
      "Exceto": "null",
      "PrecoCentavos": 75,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896204311256_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": 5,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": 98,
      "Fornecedor": "null",
      "EmbalagemReferencia": "litro",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 1,
      "Comprador": "Cassio Steffens - Limpeza",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Lava-louças Líquido Limpol 500ml",
      "Exceto": "null",
      "PrecoCentavos": 99,
      "EAN": "Q:\\Banco Imagens\\tiff\\7891022638004_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": 3,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 1,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Couve Molho Embalada",
      "Exceto": "null",
      "PrecoCentavos": 29,
      "EAN": "Q:\\Banco Imagens\\tiff\\7898941857035_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 1,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Moranga Cabotiá Inteira",
      "Exceto": "null",
      "PrecoCentavos": 89,
      "EAN": "Q:\\Banco Imagens\\tiff\\21661_1.tif",
      "EmbalagemMarketing": "kg",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 1,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Batata Branca",
      "Exceto": "null",
      "PrecoCentavos": 98,
      "EAN": "Q:\\Banco Imagens\\tiff\\20251_1.tif",
      "EmbalagemMarketing": "kg",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 2,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Chuchu",
      "Exceto": "null",
      "PrecoCentavos": 29,
      "EAN": "Q:\\Banco Imagens\\tiff\\20855_1.tif",
      "EmbalagemMarketing": "kg",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 2,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Laranja Suco",
      "Exceto": "null",
      "PrecoCentavos": 39,
      "EAN": "Q:\\Banco Imagens\\tiff\\2110_1.tif",
      "EmbalagemMarketing": "kg",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 2,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Cebola Nacional",
      "Exceto": "null",
      "PrecoCentavos": 49,
      "EAN": "Q:\\Banco Imagens\\tiff\\8389_1.tif",
      "EmbalagemMarketing": "kg",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": 36,
      "Fornecedor": "null",
      "EmbalagemReferencia": "kg",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 2,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Brócolis Híbrido Embalado 250g",
      "Exceto": "null",
      "PrecoCentavos": 59,
      "EAN": "Q:\\Banco Imagens\\tiff\\7898994655114_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": 10,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 3,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Banana-prata",
      "Exceto": "null",
      "PrecoCentavos": 79,
      "EAN": "Q:\\Banco Imagens\\tiff\\1342_1.tif",
      "EmbalagemMarketing": "kg",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 5,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Melão Cepi",
      "Exceto": "null",
      "PrecoCentavos": 99,
      "EAN": "Q:\\Banco Imagens\\tiff\\39727_1.tif",
      "EmbalagemMarketing": "kg",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": 96,
      "Fornecedor": "null",
      "EmbalagemReferencia": "kg",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 8,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Uva Preta sem Semente 500g",
      "Exceto": "null",
      "PrecoCentavos": 98,
      "EAN": "Q:\\Banco Imagens\\tiff\\7898060741666_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": 17,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": 44,
      "Fornecedor": "null",
      "EmbalagemReferencia": "litro",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 3,
      "Comprador": "Mauro H Kaiser",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Cerveja Eisenbahn Puro Malte Pilsen Latão 473ml",
      "Exceto": "null",
      "PrecoCentavos": 99,
      "EAN": "Q:\\Banco Imagens\\tiff\\7898367983356_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": 8,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 17,
      "Comprador": "Renilson Lesnik Cyganski",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Costela Bovina Em Tira Congelada",
      "Exceto": "null",
      "PrecoCentavos": 95,
      "EAN": "Q:\\Banco Imagens\\tiff\\55758_1.tif",
      "EmbalagemMarketing": "kg",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": 71,
      "Fornecedor": "null",
      "EmbalagemReferencia": "kg",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 19,
      "Comprador": "Renilson Lesnik Cyganski",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Batata McCain Tradicional Congelada Leve 1,7kg Pague 1,5kg",
      "Exceto": "null",
      "PrecoCentavos": 90,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896105800835_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": 11,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": 58,
      "Fornecedor": "null",
      "EmbalagemReferencia": "kg",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 2,
      "Comprador": "Vilmar Klamt",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Massa Todeschini Sêmola Espaguete 500g",
      "Exceto": "null",
      "PrecoCentavos": 79,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896022205775_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": 5,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": 50,
      "Fornecedor": "null",
      "EmbalagemReferencia": "kg",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 2,
      "Comprador": "Vilmar Klamt",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Biscoito Biscobom Maria 260g",
      "Exceto": "null",
      "PrecoCentavos": 99,
      "EAN": "Q:\\Banco Imagens\\tiff\\7898209650453_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": 11,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": 6,
      "Fornecedor": "null",
      "EmbalagemReferencia": "kg",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 4,
      "Comprador": "Cassio Steffens - Bazar",
      "FiliaisSemMix": "17,29,77",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Substrato para Plantas Verdão 1,5kg/2kg",
      "Exceto": "null",
      "PrecoCentavos": 59,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896762200580_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": 3,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": 99,
      "Fornecedor": "null",
      "EmbalagemReferencia": "kg",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 5,
      "Comprador": "Cassio Steffens - Bazar",
      "FiliaisSemMix": "17,29,77",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Casca de Pinus Pedra Nobre Rolada 1kg",
      "Exceto": "null",
      "PrecoCentavos": 99,
      "EAN": "Q:\\Banco Imagens\\tiff\\7898325500076_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": 5,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": 92,
      "Fornecedor": "null",
      "EmbalagemReferencia": "kg",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 9,
      "Comprador": "Cassio Steffens - Bazar",
      "FiliaisSemMix": "17,29,77",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Substrato para Plantas Verdão 5kg",
      "Exceto": "null",
      "PrecoCentavos": 59,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896762205004_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": 1,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 9,
      "Comprador": "Cassio Steffens - Bazar",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Pulverizador Sanremo Rosa 580ml",
      "Exceto": "null",
      "PrecoCentavos": 90,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896359025121_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": 30,
      "Fornecedor": "null",
      "EmbalagemReferencia": "litro",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 18,
      "Comprador": "Cassio Steffens - Bazar",
      "FiliaisSemMix": "17,29,77",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Regador Nutriplan Azul 3L",
      "Exceto": "null",
      "PrecoCentavos": 90,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896403218561_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": 6,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "litro",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 1,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Adubo Líquido Isla 5ml",
      "Exceto": "null",
      "PrecoCentavos": 99,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896026023429_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": 398,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 1,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Semente Isla",
      "Exceto": "null",
      "PrecoCentavos": 99,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896026012096_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 2,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Kalanchoe Dobrado Míni Vaso 06",
      "Exceto": "null",
      "PrecoCentavos": 49,
      "EAN": "Q:\\Banco Imagens\\tiff\\7890291177061_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 2,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Suculenta Vaso 06",
      "Exceto": "null",
      "PrecoCentavos": 49,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896553686425_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 3,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Violeta Vaso 11",
      "Exceto": "null",
      "PrecoCentavos": 99,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896553640014_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 6,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Gérbera Vaso 14",
      "Exceto": "null",
      "PrecoCentavos": 98,
      "EAN": "Q:\\Banco Imagens\\tiff\\7890291254830_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 8,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Kalanchoe Dobrado Vaso 15",
      "Exceto": "null",
      "PrecoCentavos": 98,
      "EAN": "Q:\\Banco Imagens\\tiff\\7890291141055_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 9,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Girassol Sun Bright Míni Vaso 15",
      "Exceto": "null",
      "PrecoCentavos": 98,
      "EAN": "Q:\\Banco Imagens\\tiff\\7890291138529_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 12,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Bambu-da-sorte Vaso 06",
      "Exceto": "null",
      "PrecoCentavos": 99,
      "EAN": "Q:\\Banco Imagens\\tiff\\7890291451215_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 13,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Roseira Míni Vaso 13",
      "Exceto": "null",
      "PrecoCentavos": 90,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896553664263_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 19,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Antúrio Variado Vaso 15",
      "Exceto": "null",
      "PrecoCentavos": 90,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896553613452_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 19,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Echeveria Cuia 21",
      "Exceto": "null",
      "PrecoCentavos": 90,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896553649772_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 19,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Peperômia Scandens Cuia 21",
      "Exceto": "null",
      "PrecoCentavos": 90,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896553659757_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 29,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Palmeira Raphis  Vaso 17",
      "Exceto": "null",
      "PrecoCentavos": 90,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896553644357_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 32,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Zamioculca Vaso 17",
      "Exceto": "null",
      "PrecoCentavos": 90,
      "EAN": "Q:\\Banco Imagens\\tiff\\7896553627145_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    },
    {
      "EAN2": "null",
      "PrecoReferenciaCentavos": null,
      "Fornecedor": "null",
      "EmbalagemReferencia": "null",
      "PrecoCentavosFaixa": "null",
      "DescricaoPackVirtual": "null",
      "PrecoReais": 37,
      "Comprador": "Dieison Kunzel",
      "FiliaisSemMix": "null",
      "PrecoReaisFaixa": "null",
      "QuantidadeMinima": null,
      "DescricaoProduto": "Orquídea Phalaenopsis Vaso 12",
      "Exceto": "null",
      "PrecoCentavos": 90,
      "EAN": "Q:\\Banco Imagens\\tiff\\7890291325219_1.tif",
      "EmbalagemMarketing": "cada",
      "Lote": "null",
      "PrecoReferenciaReais": null,
      "Observacao": "null",
      "TipoPagina": "null"
    }
  ]